Fix/calculate aircrew time
airmencoders/Logging-iOS pull request #127
Opened 2020-12-22 23:03 UTC by petermisik

Updated HelperFunctions with the math to sum the row.

2020-12-22 23:38 UTC, Pete-Hoch reviewed
Just a couple of questions. (And suggestions.)

2020-12-22 23:38 UTC, Pete-Hoch commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> -        time.text = crewMember.time
It looks like we never use this anymore. (But we do set it in the constructor.)

Should we remove the field from CrewMember?

2020-12-22 23:38 UTC, Pete-Hoch commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> +        time.text = Helper.airCrewTotalTimeCalculation(crewMember: crewMember)
How about making this a function in CrewMember? Something like:

crewMember.totalAirTime().

2020-12-23 00:56 UTC, jbethanco commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> +        time.text = Helper.airCrewTotalTimeCalculation(crewMember: crewMember)
I'm having a hard time getting past our data model using strings for what should be doubles, ints, or dates. Have we thought about refactoring this? Converting from and to strings to do math isn't ideal.

2020-12-23 03:27 UTC, Pete-Hoch commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> +        time.text = Helper.airCrewTotalTimeCalculation(crewMember: crewMember)
> I'm having a hard time getting past our data model using strings for what should be doubles, ints, or dates. Have we thought about refactoring this? Converting from and to strings to do math isn't ideal.

Understood, but we are likely to change persistence over to Core Data (or something) after 0.1.0 and we will be able to do that all at once. We can even add formatters to the text fields so the user can't even type a character in a numeric field. But again, this has all been very quickly put together and there is little reason to put a lot of time into the current UI when we plan to totally replace it by mid January.

At that point, we can address the data model and what makes the most sense.

2020-12-23 03:51 UTC, jbethanco commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> +        time.text = Helper.airCrewTotalTimeCalculation(crewMember: crewMember)
Sounds good!

2020-12-23 17:46 UTC, petermisik commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> -        time.text = crewMember.time
I don't think we need to remove it from CrewMember.  This data needs to be attached to the model and part of the storage.

2020-12-23 18:23 UTC, petermisik commented on Logging/Controllers/View Controllers/Split Time/FlightTimeTableViewCell.swift
> +        time.text = Helper.airCrewTotalTimeCalculation(crewMember: crewMember)
Changes are in the new PR.

2020-12-23 18:45 UTC, jbethanco requested changes
Looks good other than the tests needing an update. 
And just FYI: I believe Pete H is wanting two reviews prior to merges till 0.1.0

2020-12-23 18:45 UTC, Pete-Hoch requested changes
Need to fix up unit tests.

2020-12-23 18:46 UTC, jbethanco approved these changes

2020-12-23 18:57 UTC, Pete-Hoch approved these changes
Looks good!

2020-12-23 19:05 UTC, merged