added side menu and other smaller views
airmencoders/Logging-iOS pull request #141
Opened 2021-01-04 21:53 UTC by bmorris-revacomm

- added side menu view
- added side menu button view
- added form view
- added custom fonts
- added custom font views
- edited header view and body view to adjust sizing/spacing

2021-01-04 21:55 UTC, bmorris-revacomm commented
For some reason, it looks like it added the whole testing file? Not sure why that happened?

2021-01-04 23:57 UTC, Pete-Hoch requested changes
Many of our names colors do not have a dark mode variant. We should just use the current universal in dark mode and see how it looks.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/ContentView.swift
>              // This is probably wring as we want the body to run the
This comment was for the spacer, so let's get rid of it too.

2021-01-04 23:57 UTC, Pete-Hoch commented on LoggingTests/Form781ControllerTests.swift
> +
I don't think we want this file in the repository.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/BodyView.swift
> +            SideMenu()
What do you think of SideView (instead of menu), it is more than just a menu.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/DarkBoldText.swift
> +    }
Please add a preview for dark mode.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/FormView.swift
> +    }
Please add a preview for dark mode.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/HeaderView.swift
> +                .padding(.leading)
Looks much nicer.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/HeaderView.swift
> -                .font(Font.system(.headline))
Clearly I was looking at an old speck. Thanks for the clean up.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/SideMenu.swift
> +                SideMenuButton(text: "AIRCREW LIST")
Add "AIRCREW DATA".

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/SideMenuButton.swift
> +    }
Please add a Dark Mode preview.

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/SideMenuButton.swift
> +            print("SideMenuButton tapped")
Since each button will have a different action, we should think about what to do here.

We can either init the button with a selector to call some action function, or init with a message that gets broadcast. Or...? What feels right for us?

2021-01-04 23:57 UTC, Pete-Hoch commented on PBLogging/Views/WhiteBoldText.swift
> +    }
Please add a dark mode preview

2021-01-05 15:42 UTC, bmorris-revacomm commented on PBLogging/Views/SideMenuButton.swift
> +            print("SideMenuButton tapped")
I'm good with whatever you think is best!

2021-01-05 17:29 UTC, jbethanco reviewed
Please check this out:
https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-a-sidebar-for-ipados

As opposed to using an HStack with a sidebar and body, Wrapping it in a NavigationView gives us the sidebar, navigation, animations, and rotation compensation for free. Then our side buttons become NavigationLinks and we get all the view nav for free.

2021-01-05 18:03 UTC, jbethanco commented
> Please check this out:
> https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-a-sidebar-for-ipados
> 
> As opposed to using an HStack with a sidebar and body, Wrapping it in a NavigationView gives us the sidebar, navigation, animations, and rotation compensation for free. Then our side buttons become NavigationLinks and we get all the view nav for free.

Oops. While the NavigationView will be available to us, that ".listStyle(SidebarListStyle())" will not be till iOS 14.

2021-01-05 18:23 UTC, Pete-Hoch approved these changes
This is a great start.

Let's get it in and then start to fill out the function of the pieces.

2021-01-05 18:23 UTC, jbethanco commented
> > Oops. While the NavigationView will be available to us, that ".listStyle(SidebarListStyle())" will not be till iOS 14.
> 
> Good point, we do need to be careful to avoid iOS 14 stuff.

That was Misik's good catch.

2021-01-05 18:26 UTC, merged