round training event corners - PBS-771
airmencoders/Logging-iOS pull request #298
Opened 2021-03-16 15:00 UTC by bmorris-revacomm

- create View extension and custom shape to allow rounding specific corners
- refactor if statement for PersonStepperRow to round corners for first and last in group

2021-03-16 18:15 UTC, jbethanco requested changes

2021-03-16 18:15 UTC, jbethanco commented on PBLogging/Views/TabViews/TrainingEventsTab/TrainingStepperView.swift
> +            } else if personEvent.isLastInGroup {
Let's pair up after your appointment and figure out how to do this without the else if else

2021-03-16 18:16 UTC, jbethanco commented on PBLogging/Views/TabViews/TrainingEventsTab/TrainingStepperView.swift
> +            } else if personEvent.isLastInGroup {
But I love how it looks.

2021-03-16 18:31 UTC, Pete-Hoch commented on PBLogging/Views/TabViews/TrainingEventsTab/TrainingStepperView.swift
> +            } else if personEvent.isLastInGroup {
Agreed, it looks great.

Perhaps replace  isFirstInGroup &  isLastInGroup with roundedCorners and then the item can return none, top, bottom or something like that.

Anyway, very cool looking.

2021-03-17 17:55 UTC, jbethanco submitted a review, later dismissed

2021-03-17 18:36 UTC, petermisik commented on PBLogging/Extensions/View+Ext.swift
> +
I love this extension.  Nice work.

2021-03-17 18:38 UTC, petermisik approved these changes
Looks fantastic.  Everything lines up and looks great!

2021-03-17 18:43 UTC, merged