generate PDF in the background (mostly)
airmencoders/Logging-iOS pull request #368
Opened 2021-04-22 01:55 UTC by Pete-Hoch

This pust the majority of out PDF generation on a background thread. The PDF gneration is stand alone now and I updated the 781Form structures to hold all of the data we need. So there is no coredata access while rendering the PDF. I also added to the callback method to return a % complete value that the calling method can use or not as it wishes. Currently I just print out the percent donw value.

There are two items that still can not be run on the background thread.

TrainingEventsPDFView(crewMember:) & TrainingEventsSummaryPDFView(eventsAndTotals:)

These are using SwiftUI and must be run on the foreground. 

I see two ways to solve this, but since they are isolated, I wanted to get the rest of this out for review.

To fix the main trheasd rendering requirement I see two ways to go.

1) Make an image context and use core graphics (moslty AttributedString and MoveTo/LineTo) to draw into the context. Then convert the image to a PDF page as we do now.

2) Make some new PDF docs for the Training Events and Training Even Summary pages and fill the data just like we currently do for the 871.

Thoughts? Comments?

2021-04-22 07:00 UTC, jbethanco requested changes
I like the cancellation ability. 
Training event pages are still showing up blank for me here. 
The completion percentages are unused.

2021-04-22 19:05 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            let pageCount: Double = (Double(forms.count) * 2.0) + Double(crewMembers.count) + 1
sure

2021-04-22 19:51 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            var currentPage: Double = 1
ditto

2021-04-22 20:23 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    static let share: PDF = PDF()
static works.

2021-04-22 20:26 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
Note to self: Cancel (one l) Cancelled (two l's).

As to the point of the function, it was just to remove some clutter from the already very full function.

2021-04-22 20:27 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +                //completion(.failure(.badPDF))
Done

2021-04-22 20:28 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            //completion(.failure(.badPDF))
ditto

2021-04-22 20:28 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +        //completion(.success(outputFileURL))
got it

2021-04-22 20:28 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            //completion(.failure(.badURL))
yes

2021-04-22 20:29 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    static let share: PDF = PDF()
removed and went with static functions

2021-04-22 20:31 UTC, Pete-Hoch commented on PBLogging/Data/Form781.swift
> +func convertMERS(_ mirs: [MissionEventRecord]) -> [MissionEventsRec] {
Auto correct?

Changed mis(s) to mer(s).

2021-04-22 21:05 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +                    callBack(.success((percentDone, nil, nil)))
A quick search did not show a way to add .progess to Result, so I broke it out into a progress call back and the Result completion block. I think this is clearer now.

2021-04-22 21:06 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    func reset() {
renamed cancel()

2021-04-22 21:07 UTC, Pete-Hoch commented on PBLogging/Views/UtilityViews/PDFPreviewView.swift
> +                        if let url781 = url781 {
Fixed the optional and added progress string call back.

2021-04-22 21:09 UTC, Pete-Hoch commented on PBLogging/Views/UtilityViews/PDFPreviewView.swift
> +                        print(error.description())
Added an error message on the screen.

2021-04-22 21:49 UTC, Pete-Hoch commented on PBLogging/Data/EntityExtensions/Event+Form781s.swift
> +                tempAC.events                             = crewLine.person.dailyTrainingEvents(for: self)
OK, I have reverted this to use the code to generate the list from the coredata instead of stashing things in the form.

2021-04-22 21:59 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +                    }
Cleaned up a little. But also reverted to the original code that uses the event and sorties.

2021-04-23 03:46 UTC, Pete-Hoch commented
All feedback has been addressed.

2021-04-24 02:22 UTC, jbethanco commented
> I like the cancellation ability.
> Training event pages are still showing up blank for me here.
> The completion percentages are unused.

It appears the training events show up blank if you generate the pdf while in dark mode. I'm thinking the SwiftUI generation code is making the foreground color white for the text and then it appears white on white.

2021-04-24 04:10 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    func generate(for forms: [Form781], callBack: @escaping (Result<(Int, URL?, URL?), PDFGenError>) -> Void) {
This function is doing multiple differing things. I'm thinking it would be best if each form generation could happen in its own testable function with a single responsibility. The function that handles the logic of generating the 781s should not be the same function as the one that generates the training events. 

Taking a step back and looking at the overall architecture, where we are trying to use it, and how complex it is becoming, it probably makes since to make this class into an ObservableObject. We can then have progress properties for each of the unique functions as opposed to any callbacks. Our SwiftUI Preview view can then just bind to these properties and update accordingly.  This would prevent us from passing around values in callbacks and simplify the code. 

The @Published properties just need to be updated from the background threads on to the main thread. For example:
DispatchQueue.main.async {
    self.form781progress = 0.82 
}

This will require the class behave as a normal class and not a namespace for static functions. Which will have the added benefit of allowing us to deallocate explicitly when the preview disappears.

2021-04-24 04:27 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
This kind of baffled me still until I tried to use it. Upon looking into it more, there is really no point in using the DispatchWorkItem cancel method as it doesn't cancel the operation. 
"Cancellation does not affect the execution of a work item that has already begun"
https://developer.apple.com/documentation/dispatch/dispatchworkitem/1780910-cancel

However it seems you are using isCancelled as a flag to determine when to bail out. We could move this to a static var of the PDF class, initialized to false, and then the code would be less cluttered, and eliminate two functions in lieu of a property. Can't really see the use of a DispatchWorkItem.

2021-04-24 04:39 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +            }
If we are jumping back to main to generate these, it would probably read more cleanly to generate these on main prior to calling the background function and then pass them in. This way the background function is a background function instead of a hybrid.

2021-04-24 04:41 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    }
If we keep this whole class as a static func/var namespace (Which I hope we don't) All of this can be removed if we add a single "isCancelled" static var initialized to false and use that instead of the workitem.

2021-04-24 04:42 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +                DispatchQueue.main.sync {
UI update things are typically async as we have no need to wait for them to complete.

2021-04-24 04:42 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +            }
UI update things are typically async as we have no need to wait for them to complete.

2021-04-24 04:48 UTC, jbethanco commented on PBLogging/Views/UtilityViews/PDFPreviewView.swift
> +                                    }
This causes the "pdfURL" to updated on a background thread. Anything touching the UI should be updated on the main thread. The easy fix would be to... within the combinePDF function, have it go to the background, and then update the pdfURL on the main thread. Or maybe more explicit/better, have the combinePDFs function return the final url and then dispatch to the main thread here, so the reader can easily know what is going on thread-wise.

2021-04-24 05:12 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
I am using DispatchWorkItem becasue it does have a cencel flag. So there is something to test for.

I think computed variable vs function is a non differnce.

2021-04-24 05:13 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            }
The goal is to make all of them eventually run in the background. So this is a structure for enabling that.

2021-04-24 05:14 UTC, Pete-Hoch commented
> > I like the cancellation ability.
> > Training event pages are still showing up blank for me here.
> > The completion percentages are unused.
> 
> It appears the training events show up blank if you generate the pdf while in dark mode. I'm thinking the SwiftUI generation code is making the foreground color white for the text and then it appears white on white.

Good catch! This is a bug in 1.1.0. I have fixed it here.

2021-04-24 05:17 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    }
The whole point is that it's the workitem that is communicating to us that the operation was canceled.

2021-04-24 05:18 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            }
If these messages are sent back async, they can bunch up and the user is flodded with feedback. That was why I changed then to sync.

2021-04-24 05:19 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +                DispatchQueue.main.sync {
If these messages are sent back async, they can bunch up and the user is flodded with feedback. That was why I changed then to sync.

2021-04-24 05:24 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
I understand that. Yet due to how it is used here, it is just a harder to reach property. If moved to a static var on the class, you won't have to unwrap it or have additional functions to use it. A cancel flag is just a boolean somewhere. No need for a DispatchWorkItem or the property if we aren't using the functionality provided by DispatchWorkItem.

2021-04-24 05:25 UTC, Pete-Hoch commented on PBLogging/Views/UtilityViews/PDFPreviewView.swift
> +                                    }
Sounds good, fixed.

2021-04-24 05:33 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    }
Right, but it communicates this as boolean variable that could be held anywhere. If not using DispatchWorkItem to add a completion handle or execution dependencies, there doesn't seem to be a point in using it versus just a background call and a bool flag that does not need to be unwrapped with guards and if lets. It can be set directly instead of by a function. It eliminates tens of lines of code and multiple functions. The workItem provides no utility here other than providing something to hold the boolean flag.

2021-04-24 05:46 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +                DispatchQueue.main.sync {
I don't know what you mean by "bunch up." The goal is to flood the user with realtime feedback concerning the background thread as it happens. There is nothing to bunch up. The UI changes immediately upon receipt of the change. The goal of the background thread is to be as performant as possible without locking the UI. If we delay the background thread while waiting on UI updates, we aren't meeting that goal. The difference between sync and async here is not what is presented to the user. It is only what this background thread is waiting on before continuing. There is no reason to wait for the main thread to update the UI before proceeding on this background thread.

2021-04-24 05:46 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +            }
See previous comment.

2021-04-24 08:45 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +                DispatchQueue.main.sync {
I think I found what you may have been trying to prevent with the sync call. It was showing "4 of 3 pages" as the variable counting pages was changing shortly after the call out of the thread. The key there is to not send variables out of the thread. Build the string and then send the string to the main thread so that it isn't changed after. With the string interpolation, it seems it is looking at the memory address. Alternatively, change the counting logic so the increment is before the external call.

2021-04-25 07:25 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
https://stackoverflow.com/questions/48280851/how-to-stop-execution-of-a-running-background-thread-from-main-thread-on-swift-w

This works, I do not understand your objections.

2021-04-25 07:26 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    }
https://stackoverflow.com/questions/48280851/how-to-stop-execution-of-a-running-background-thread-from-main-thread-on-swift-w

2021-04-25 07:32 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +                DispatchQueue.main.sync {
Yes! Beautiful. Great idea, fixed.

2021-04-25 07:33 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +            }
Yes, great, all progress calls are async now. Thanks!

2021-04-25 08:02 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
A person on stack overflow saying it works... does not mean it works. 
If you use the code they gave, it does not. 
If it did work, you wouldn't have to check for the "isCancelled" boolean in your code to return from the work item. 

Try running this in a playground (It's the code from stack overflow, with some print statements to show work.)
```
import UIKit

let workItem = DispatchWorkItem {
    //.... writing stuff in background ....
    
    for i in 0...5 {
        print(i)
        sleep(1)
    }
    
    DispatchQueue.main.async {
        //.... done writing stuff, updating ui ....
        print("updating UI")
    }
}

DispatchQueue.global().async(execute: workItem)
print("cancelling")
workItem.cancel()
print("after cancelled")
DispatchQueue.global().async(execute: workItem)
DispatchQueue.global().async(execute: workItem)

```
This is what I get when I run it here. 

> cancelling
> 0
> after cancelled
> 1
> 2
> 3
> 4
> 5
> updating UI


If the cancelling worked, there should be nothing after the "after cancelled"

It runs as I previously said as Apple's documentation says it runs, "Cancellation causes future attempts to execute the work item to return immediately. Cancellation **does not affect the execution of a work item that has already begun.**" 

This is why the additional execute items do not have any effect. 
If you remove "workItem.cancel()" you will notice the counter run three times concurrently resulting in: 

> cancelling
> 0
> after cancelled
> 0
> 0
> 1
> 1
> 1
> 2
> 2
> 2
> 3
> 3
> 3
> 4
> 4
> 4
> 5
> 5
> 5
> updating UI
> updating UI
> updating UI

2021-04-25 08:05 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    }
Please see previous comment.

2021-04-25 23:55 UTC, Pete-Hoch commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
I think you have a missunderstanding of how the background task is canceled. From Apple's own documentation, if the block is alredy executing, it is not touched. The cancel will however prevent the block from running if it is canceled before the schedualer starts execution on the block. But we can exit the block early if the user has done something that means we should cancel the operation. (Like hitting the back button.)

So, the question is, how best to do this?  Here is an article that talks about two ways to cancel a background task.

https://jordansmith.io/cancelling-background-tasks/

I believe this explains why using a DispatchWorkitem is more thorough.

2021-04-26 03:34 UTC, jbethanco commented on PBLogging/Utilities/PDF.swift
> +    private func isCanceled() -> Bool {
I'm not sure what you think I misunderstand how the background task is cancelled? You provided a stackoverflow link showing that "it works." I provided you demo code showing that it doesn't work as shown in the stack overflow post. That was my only intent there. I understand that one can use a boolean flag to bail out of a background task as we've discussed it previously.  

I've just read the article that you believe, "explains why using DispatchWorkItem is more thorough."
I'm not sure how it is more thorough based on that article? 
The article describes using DispatchWorkItem to cancel future work, which is not how you have used it in our app.  The way it is currently in our code, is unlike anything in this article and not using any benefits of DispatchWorkItem. 

In our code, you execute the DispatchWorkItem directly after its creation. This relegates its cancel() function to a setter, with no other functionality. This eliminates the functionality described in the article.

At that moment, there was no benefit to using DispatchWorkItem. We aren't using its cancellation functionality, its notifications, or wait methods.
I would hope we could agree that when we use a class, we use it for its intended purpose, and if we don't need its functionality we don't use it. 

A couple of days ago, I wrote: https://github.com/airmencoders/Logging-iOS/pull/368#discussion_r619581924

It describes what could be a fairly clean/declarative way of handling our background woes, without relying on callbacks. We could also possibly execute multiple tasks concurrently. We will still need a boolean flag for cancellation.

2021-04-27 02:54 UTC, closed without merging