Add Night Time Calculation to Flight Conditions
airmencoders/Logging-iOS pull request #375
Opened 2021-04-27 17:20 UTC by jbethanco

Add ability to get latitude and longitude from ICAO
-Add decodable AirfieldsStruct
-Add airfields json file, with intentionally wrong file extension (large json files crash Xcode if opened)

Add CLLocationCoordinate2D extension file with multiple calculating functions
Add extension on Double to go to and from radians and degrees
Add night calculator enum to hold the night calculating functions
Add button to auditor view to calculate the night hours
Add info button, and popover, to night hours calc button, to describe what it does

![Simulator Screen Recording - _iPad Pro 9 7 v 14 5 - 2021-04-27 at 07 19 56](https://user-images.githubusercontent.com/76016626/116284670-08ea4280-a729-11eb-83a0-1557dcbff673.gif)

2021-04-27 18:08 UTC, cbrech commented
Can we put the calculate button above like gonkulate is?

2021-04-27 18:09 UTC, jbethanco commented
> Can we put the calculate button above like gonkulate is?

sure.

2021-04-27 18:50 UTC, jbethanco commented
> > Can we put the calculate button above like gonkulate is?
> 
> sure.

done.

2021-04-28 18:27 UTC, bmorris-revacomm requested changes

2021-04-28 18:27 UTC, bmorris-revacomm commented on PBLogging/Views/TabViews/FlightTimeTab/AuditingFlightTimeView.swift
> +        Text("If able, this button populates your night hours (between the end of evening civil twilight and beginning of morning civil twilight) with those calculated based on interpolated positions
Need a space after "positions"

2021-04-28 18:39 UTC, jbethanco commented on PBLogging/Views/TabViews/FlightTimeTab/AuditingFlightTimeView.swift
> +        Text("If able, this button populates your night hours (between the end of evening civil twilight and beginning of morning civil twilight) with those calculated based on interpolated positions
good catch.

2021-04-28 18:42 UTC, bmorris-revacomm approved these changes
Looks good to me 🦄

2021-04-28 18:56 UTC, merged