Fix/fetch from pbl api
airmencoders/Logging-iOS pull request #430
Opened 2021-06-10 13:39 UTC by petermisik

Changed PBSEvent model to use Codable
Changed PBSCrew model to use Codable
Altered DataController to absorb Sorite Mission number, takeoff time, and land time.
Created Extension to make our JSON prettyPrinted.
Updated PBSEventCard and ImportEvents to use the new models.

2021-06-10 15:10 UTC, jbethanco requested changes
Not looking ready for primetime. Tried to add an event and got a crash here: 
![image](https://user-images.githubusercontent.com/76016626/121549988-f3c52c80-c9d3-11eb-8d3d-7ac2335aea17.png)

A lot of commented out code. The JSON.swift file and the old data models all need to be removed. There seems to be some things that are observed objects/published vars that don't need to be.

2021-06-15 23:58 UTC, petermisik commented on PBLogging/Network/PBSModels.swift
> +//                print("JSON: \(data.prettyPrintedJSONString!)")
A lot of clean up between Sam and I.  Refactored and removed unused code.

2021-06-16 04:36 UTC, jbethanco approved these changes
It is working, but may still need some cleanup.

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Network/ImportEventsView.swift
> +        NavigationLink(destination: PBSEventsView(isShown: $isShown, events: events).environmentObject(dataController)) {
.environmentObject modifier should be on next line.

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Network/PBSModels.swift
> +    /// The following is for Swift UI previews.
If for previews, maybe just include in the preview struct.

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Network/SampleJSONData.swift
> +class SampleJSONData {
Does this need to be a class? If we don't need inheritance or reference types, no need for a class. This looks like this should be an enum.

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Network/SampleJSONData.swift
> +//  Created by Pete Rogers on 6/15/21.
Who is Pete Rogers?

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Network/ImportEventsView.swift
>  struct CardModifier: ViewModifier {
Unused modifier

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Data/DataController.swift
>              print("GREAT SUCCESS >>> \(crewLine)")
I'm bad about forgetting to remove these. Probably good to delete or if must haves for some reason, give them some context as to what is happening.

2021-06-16 04:36 UTC, jbethanco commented on PBLogging/Network/PBSModels.swift
> +        }
This is a lot of supporting code for the previews as well as the JSON sample data. When I run the previews, they don't work. Probably should remove the supporting code and sample JSON data if the previews do not work. Add back when they do?

2021-06-16 04:38 UTC, jbethanco commented on PBLogging/Network/ImportEventsView.swift
>      @State var dataModel: PBSUser?
if the datamodel is a PBSUser, might be worth calling it pbsUser for clarity.

2021-06-16 04:40 UTC, jbethanco commented on PBLogging/Network/ImportEventsView.swift
> +    private func checkDataModel(dataModel: PBSUser?, orgs: [String: String]?, events: [PBSEvent]?) {
Function name could be more clear, it's checking the dataModel which is a PBSUser, checking the orgs, and events and then downloading them if they are nil. "checkDataModel(...) at the call site does not inform the reader what is actually happening.

2021-06-16 04:42 UTC, jbethanco commented on PBLogging/Network/PBSModels.swift
> +       static let sampleUserOneOrg: PBSUser = {
Indentation of this file is off.

2021-06-16 14:05 UTC, petermisik commented on PBLogging/Network/SampleJSONData.swift
> +//  Created by Pete Rogers on 6/15/21.
Got to love blindly replacing a word.

2021-06-16 14:06 UTC, petermisik commented on PBLogging/Network/ImportEventsView.swift
>  struct CardModifier: ViewModifier {
Removed.

2021-06-16 14:31 UTC, petermisik commented on PBLogging/Network/PBSModels.swift
> +    /// The following is for Swift UI previews.
Commented out previews with a TODO.  Will resolve in the next sprint.

2021-06-16 15:24 UTC, merged