Sort Missions by date, add date to mission card, update sortie sort, remove scroll manager
airmencoders/Logging-iOS pull request #440
Opened 2021-06-17 14:09 UTC by Adam-Roney581

- Add [date label to mission card](https://www.figma.com/file/L0iJ4e3M6lcwi1UvUawoLs/PBL---Swift-UI-Designs?node-id=1101%3A863). Shows the most recent sortie takeoff time. If there's no sortie/valid takeoff time, it shows the current date
- Sort missions by my most recent sortie takeoff time. If no sortie/valid takeoff time, show mission at the top of the list
- Updated sortie sort to show the most recent sortie at the top. If there's no takeoff time (or a new sortie) it shows at the top
- Removed scroll manager stuff since we're adding everything to the top of the list and sorting by most recent 
- Updated UI tests

2021-06-18 04:54 UTC, jbethanco requested changes

2021-06-18 04:54 UTC, jbethanco commented on PBLogging/Views/Overview/MissionCard.swift
> +            }
I think this could be deleted and the method will have the same result.

2021-06-18 04:54 UTC, jbethanco commented on PBLogging/Views/Overview/MissionListView.swift
> +            var secondTakeoffTime: Date?
My tiny screen wouldn't let me select more.  
This should probably all  be abstracted away in a Comparable extension on Mission as opposed to code in a view.
However this seems overly complicated for what we are trying to accomplish. We may be able to simplify this a bit.  
If we conform mission to comparable, then we can change the fetch request to sort for us. That return the delete function back to normal as well. If you tried this and it didn't work for some reason, please let me know.

2021-06-23 18:31 UTC, Adam-Roney581 commented on PBLogging/Views/Overview/MissionCard.swift
> +            // Today's date
This has been removed

2021-06-23 18:32 UTC, Adam-Roney581 commented on PBLogging/Views/Overview/MissionCard.swift
> +            .foregroundColor(Color.pblForegroundSecondary)
Fixed

2021-06-23 18:32 UTC, Adam-Roney581 commented on PBLogging/Views/Overview/MissionCard.swift
> +            }
This has been removed

2021-06-23 18:33 UTC, Adam-Roney581 commented on PBLogging/Views/Overview/MissionListView.swift
> +            var secondTakeoffTime: Date?
Added a new data model attribute like we discussed and it is now sorting by that. Also the delete function is back to normal

2021-06-25 15:58 UTC, jbethanco commented on PBLogging/Data/EntityExtensions/Mission+Accessors.swift
> +    }
As opposed to storing the date, which could return incorrect information if a sortie date is edited, this can be a computed property. So no need to store it in missionDate_ .  Also not sure if this will return the temporal first date. Let's pair on Tuple on this if you have the time.

2021-07-01 06:37 UTC, jbethanco commented
Sent a DM on MM. I'm thinking the most reasonable way forward is to add a non optional "date created" attribute on Mission and Sortie.

2021-07-01 06:37 UTC, closed without merging