Initial commit of clean up.  Fixed call site and function.
airmencoders/Logging-iOS pull request #467
Opened 2021-07-08 14:44 UTC by petermisik

Discussion
Reworked PR-463 to remove fragile computed property that went from String -> Int -> String.  Cleaned up call sites.

Note: Put a similar property on the model to clean up the import conversion.

Add ✍️

None

Update 🔄

DataController
CrewLine+Accessors
String+Ext
ImportEventsView
PBSModels
AircrewListView

2021-07-08 15:06 UTC, bmorris-revacomm commented on PBLogging.xcworkspace/contents.xcworkspacedata
>  </Workspace>
Can you see if you can find a way to remove/delete this reference to Pods?

2021-07-08 15:23 UTC, petermisik commented on PBLogging.xcworkspace/contents.xcworkspacedata
>  </Workspace>
Removed.  Sorry about that.

2021-07-08 15:38 UTC, jbethanco requested changes
Can no longer edit existing flying orgs.

2021-07-08 15:38 UTC, bmorris-revacomm commented on PBLogging.xcworkspace/contents.xcworkspacedata
>  </Workspace>
No worries! Thank you!!

2021-07-09 06:47 UTC, jbethanco requested changes
The Flying Org field now allows alphas and numbers, but now also allows punctuation which shouldn't be allowed. We need to limit it to alphanumerics only. When typing a 5th character, it briefly shows up then disappears.  

We are doing a similar but different validation on last4 for the SSAN on the same view, I think we can use a near identical solution for the flying organization.  

The current solution in this PR adds a file for another extension on binding that limits the data to 4 characters, but then assigns it a value that is passed to a function that limits the value to 4 characters. The binding.max(4) and the paddedFourDigitsOnly() are both trimming the string to length.

2021-07-09 06:47 UTC, jbethanco commented on PBLogging/Extensions/Binding+Value.swift
> +}
What is the purpose of the async call?

2021-07-09 06:47 UTC, jbethanco commented on PBLogging/Views/SingleSortie/AircrewListView.swift
> +                    crewLine.flyingOrganization = crewLine.flyingOrganization.paddedFourDigitsOnly()
paddedFourDigitsOnly is now allowing alphas and digits, yet this function still is named with digits.

2021-07-09 18:07 UTC, jbethanco requested changes
The paddedFourCharactersOnly code isn't getting called when the user is typing. Only after they leave the field which isn't our desired result. 

The function seemed it was doing redundant work with prefix(4) and suffix(4) but suffix is being called on self instead of s, which I don't think is the intent.

2021-07-09 19:59 UTC, petermisik commented on PBLogging/Data/EntityExtensions/CrewLine+Accessors.swift
> +    }
Removed this call as it's not needed.

2021-07-09 21:05 UTC, jbethanco requested changes
![image](https://user-images.githubusercontent.com/76016626/125135838-5ed25380-e0a5-11eb-81fd-b4f14205f278.png)

There seems to be bug in the function. I think it may be on line 185 where it returns self instead of s. I'm not sure if that will fix it though. Are you testing data entry in the simulator or device for expected behavior?

2021-07-09 21:47 UTC, petermisik commented
I was testing in the sim. Didn't see this behavior. Will have an update later tonight.

2021-07-09 23:38 UTC, petermisik commented
Latest commit fixed the problem.  Tested and there seems to be no unwanted behavior.

2021-07-10 05:16 UTC, jbethanco approved these changes
It works!

2021-07-10 20:07 UTC, merged