Fix/pbs 1604 search by prefix
airmencoders/Logging-iOS pull request #523
Opened 2021-08-04 18:00 UTC by petermisik

# Discussion  💬
Current solution searches the harm location and sees if the string contains queryString.  This gives us a more granular control to provide the user the result based on the prefix of each of the words in the harm location.

# What this PR Does 🤔 
Add ability to search by Harm Location using prefix.  Gives us a generic way to search prefix on long strings and provide a boolean result.  This search ability can be used in other areas.  Add highlights to headers to indicate which field they're searching.

# Resolves 
[PBS-1604](https://jira.il2.dso.mil/browse/PBS-1604?filter=-1) - Update tails search to search by word prefix.

# Testing 🔬 
- [X] - Type the letter "C" in the field - Returns Charleston, Charlotte, and CA
- [X] - Type in "01" in the field - Returns aircraft with serial numbers beginning with 01
- [X] - Type in "UNK" - Return "No Aircraft Found"

2021-08-06 06:34 UTC, jbethanco commented
I'm not sure if highlighting the column header feels intuitive. Thinking we could bold the text of the found field. e.g. if 01-8031 is found with 01, then serial number 01-8031 is bolded. If zip code 01203 is also found with the same search, then the harm location is also bolded. Not the titles, but just the text. 

The method of highlight feels disabling to me. 
![image](https://user-images.githubusercontent.com/76016626/128466636-dcfd45a9-e418-4291-821b-fedc5fa8704d.png)

2021-08-06 06:35 UTC, jbethanco commented on PBLogging/Extensions/String+Ext.swift
> +        let characterSet = CharacterSet(charactersIn: " ,-")
I don't think the comma is necessary here.

2021-08-06 06:38 UTC, jbethanco requested changes

2021-08-06 06:38 UTC, jbethanco commented on PBLogging/Modifiers/AircraftSearchButtonModifier.swift
> +    }
Instead of highlighting the column header, I think we should be highlighting the found value in the rows. Could probably make a function that returns true if the passed in item text has a component with the prefix matching the search string. That could be used for setting the font to bold on the one item, but could also be used by the search filter.

2021-08-09 23:43 UTC, bmorris-revacomm requested changes
just some small changes!

2021-08-09 23:43 UTC, bmorris-revacomm commented on PBLogging/Modifiers/AircraftSearchButtonModifier.swift
> +        }
Again, I feel like "item" isn't descriptive enough, but I also just don't like using the word "item" for anything haha. Maybe there is a better word or better way to name the function?
Maybe something like:
fontFor(_ result: String, using queryString: String)

2021-08-09 23:43 UTC, bmorris-revacomm commented on PBLogging/Extensions/String+Ext.swift
> +        let characterSet = CharacterSet(charactersIn: " -")
Thinking maybe "componentHasPrefix" might be a better name since the built-in function is "hasPrefix" - seems more consistent. I would also put _ before queryString, so it's not left in the parameter when called.

2021-08-09 23:43 UTC, bmorris-revacomm commented on PBLogging/Extensions/String+Ext.swift
> +    }
- queryString is unused here
- I think this could use a better name? I feel like I need to look at what the function is doing to understand why this is being called. I think the word "set" threw me off? 🤔

2021-08-09 23:43 UTC, bmorris-revacomm commented on PBLogging/Modifiers/AircraftSearchButtonModifier.swift
>                                  .frame(maxWidth: 200, alignment: .leading)
this font needs to stay

2021-08-09 23:43 UTC, bmorris-revacomm commented on PBLogging/Modifiers/AircraftSearchButtonModifier.swift
> +    }
I would rename slightly to searchResults(of queryString: String)

2021-08-11 21:54 UTC, bmorris-revacomm approved these changes

2021-08-12 09:09 UTC, jbethanco approved these changes

2021-08-12 09:47 UTC, merged