Feature/beth
airmencoders/Logging-iOS pull request #60
Opened 2020-11-25 19:48 UTC by bmorris-revacomm

2020-11-26 00:25 UTC, Pete-Hoch requested changes
Mostly comments, but we should clean up some of this.

2020-11-26 00:25 UTC, Pete-Hoch commented on Logging/HelperFiles/PBLButton.swift
> +        self.titleLabel?.font = UIFont(name: FontNames.dmSansRegular, size: UIScreen.main.bounds.height/56.9)
I realize that this is targeted at the iPad, but perhaps we should have a min and max value for the font size? Maybe an extension to UIFont?

Also, what does 56.9 mean? I refer to these as 'magic numbers'. It's just a constant with no context. Do we really want a different size font in landscape vs portrait?

Minimum:

let SCALE_FONT_TO_SCREEN_SIZE = 56.9

Then use the constant. And a comment with a deeper explanation is even better.

2020-11-26 00:25 UTC, Pete-Hoch commented on Logging/HelperFiles/PBLButton.swift
> +        self.heightAnchor.constraint(equalToConstant: UIScreen.main.bounds.height/21.3).isActive = true
Yes, comment like this is good. But why is this better than just using a 64p font?

Plus there are a lot more magic numbers that follow.

2020-11-26 00:25 UTC, Pete-Hoch commented on Logging/HelperFiles/PBLButton.swift
> +        self.titleLabel?.font = UIFont(name: FontNames.dmSansBold, size: UIScreen.main.bounds.height/97.6)
Some understanding go magic number needed.

2020-11-30 15:47 UTC, petermisik commented on Logging/Controllers/View Controllers/Form 781/FlightListViewController.swift
> +        guard let form = Form781Controller.shared.forms.last else { return Alerts.showNoFormAlert(on: self) }
I'll make sure to add this to my toolbox.

2020-11-30 15:49 UTC, petermisik commented on Logging/Controllers/View Controllers/Form 781/FlightListViewController.swift
> +        else { return }
Should we add this as a bug in Jira?

2020-11-30 15:50 UTC, petermisik commented on Logging/Controllers/View Controllers/Form 781/FlightListViewController.swift
> +        flyingOrigin.text == "" ? Helper.highlightRed(textField: flyingOrigin) : Helper.unhighlight(textField: flyingOrigin)
I'll work on getting this added to Helperfunction.swift

2020-11-30 15:54 UTC, petermisik reviewed
Take a look at Pete's comments and let me know where I can help.

2020-11-30 17:09 UTC, merged