Fix/pr62
airmencoders/Logging-iOS pull request #63
Opened 2020-11-30 23:23 UTC by petermisik

2020-11-30 23:53 UTC, bmorris-revacomm approved these changes
Looks good to me!

2020-12-01 22:47 UTC, Pete-Hoch requested changes
Some conflict shrapnel in the Overview.storyboard.

2020-12-01 22:47 UTC, Pete-Hoch commented on Logging/Views/Overview.storyboard
> +>>>>>>> origin/main
This should be resolved before pushing.

2020-12-01 22:47 UTC, Pete-Hoch commented on Logging/Views/Overview.storyboard
> +>>>>>>> origin/main
Same here.

2020-12-01 22:48 UTC, Pete-Hoch commented
And you can rebase off of release/0.1.0 now.

2020-12-01 23:21 UTC, cbrech commented
Once you rebase and push new code into this PR it will re-trigger the Test workflow and on pass you will be able to merge

2020-12-03 21:28 UTC, petermisik commented
Changes made.

2020-12-03 21:54 UTC, Pete-Hoch approved these changes
Changes look good. Just clear the conflict and squash & merge!

2020-12-03 22:23 UTC, merged